tasks:
  - name: Install Python
    init: > 
      pyenv install 3.10.7 -f &&
      pyenv local 3.10.7 &&
      gp sync-done bundle
  - name: Install dependencies
    init: gp sync-await bundle
    command: pip install -r requirements.txt
  - name: Create Docker Images
    init: > 
      docker build . -f company_data_auditor.Dockerfile -t rs-alpes/company-data-auditor &&
      docker build . -f company_data_collector.Dockerfile -t rs-alpes/company-data-collector &&
      docker build . -f company_data_presenter.Dockerfile -t rs-alpes/company-data-presenter &&
      docker build . -f company_data_processor.Dockerfile -t rs-alpes/company-data-processor &&
      docker build . -f notificator.Dockerfile -t rs-alpes/notificator &&
      gp sync-done images
  - name: Create Data Folder and Grand Permissions
    init: > 
      mkdir -p data/bookkeeper && 
      mkdir -p data/zookeeper && 
      sudo chmod -R 777 ./data
  - name: Docker Compose Pull
    init: gp sync-await images
    command: docker-compose pull

ports:
  - port: 2181
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 6650
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 6650
    onOpen: ignore
